import { execFile } from 'node:child_process';
import { createHash } from 'node:crypto';
import { cp, mkdtemp, readFile, readdir, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { promisify } from 'node:util';
import { beforeAll, describe, expect, it } from 'vitest';

const run = promisify(execFile);
const repoRoot = path.join(import.meta.dirname, '..');
const cli = path.join(repoRoot, 'dist', 'cli.js');

async function copyFixture(name: string): Promise<string> {
  const dir = await mkdtemp(path.join(tmpdir(), `agent-initiator-e2e-${name}-`));
  await cp(path.join(import.meta.dirname, 'fixtures', name), dir, { recursive: true });
  return dir;
}

const init = (dir: string, ...args: string[]) => run('node', [cli, 'init', dir, '--yes', ...args]);

describe('CLI (built)', () => {
  beforeAll(async () => {
    await run('pnpm', ['build'], { cwd: repoRoot });
  }, 60_000);

  it('initialises a turborepo and is idempotent on re-run', async () => {
    const dir = await copyFixture('turborepo');
    await init(dir);

    const read = (p: string) => readFile(path.join(dir, p), 'utf8');
    expect(await read('AGENTS.md')).toContain('**Monorepo tool:** Turborepo');
    expect(await read('apps/web/AGENTS.md')).toContain('# AGENTS.md — @acme/web');
    expect(await read('CLAUDE.md')).toBe('@AGENTS.md\n');
    expect(await readdir(path.join(dir, '.claude/skills'))).toContain('add-package');
    expect(await read('docs/wiki/id/log.md')).toContain('Catatan Perubahan');

    // The manifest records the package version and a hash of every file this run wrote.
    const { version } = JSON.parse(await readFile(path.join(repoRoot, 'package.json'), 'utf8')) as { version: string };
    const manifest = JSON.parse(await read('.agents/agent-initiator.json')) as { version: string; files: Record<string, string> };
    expect(manifest.version).toBe(version);
    expect(await read('AGENTS.md')).toContain(`Generated by agent-initiator v${version}.`);
    expect(manifest.files['AGENTS.md']).toBe(`sha256:${createHash('sha256').update(await read('AGENTS.md')).digest('hex')}`);
    expect(manifest.files['package.json']).toBeUndefined();

    const before = await read('AGENTS.md');
    const second = await init(dir);
    expect(second.stdout).toContain('0 to create');
    expect(second.stdout).toContain(`Already initialised with agent-initiator v${version}`);
    expect(await read('AGENTS.md')).toBe(before);
  });

  it('keeps a hand-written AGENTS.md and prints manual instructions', async () => {
    const dir = await copyFixture('nextjs');
    await writeFile(path.join(dir, 'AGENTS.md'), '# Team notes\n');
    const { stdout } = await init(dir);
    expect(await readFile(path.join(dir, 'AGENTS.md'), 'utf8')).toBe('# Team notes\n');
    expect(stdout).toContain('AGENTS.md already exists and was kept');
    expect(stdout).toContain('.agents/rules/nextjs.md');
  });

  it('writes nothing on --dry-run', async () => {
    const dir = await copyFixture('go');
    const { stdout } = await init(dir, '--dry-run');
    expect(stdout).toContain('Dry run');
    expect(await readdir(dir)).toEqual(['go.mod']);
  });

  it('honours --preset overrides', async () => {
    const dir = await copyFixture('express');
    await init(dir, '--preset', 'typescript,hono');
    const agents = await readFile(path.join(dir, 'AGENTS.md'), 'utf8');
    expect(agents).toContain('**Stack:** TypeScript, Hono');
  });

  it('fails clearly for an unknown preset', async () => {
    const dir = await copyFixture('express');
    await expect(init(dir, '--preset', 'rails')).rejects.toMatchObject({ stderr: expect.stringContaining('Unknown preset "rails"') });
  });

  it('refuses an empty directory in --yes mode and explains the options', async () => {
    const dir = await mkdtemp(path.join(tmpdir(), 'agent-initiator-e2e-empty-'));
    await expect(init(dir)).rejects.toMatchObject({ stderr: expect.stringContaining('--framework nextjs') });
    expect(await readdir(dir)).toEqual([]);
  });

  it('creates a missing directory when presets are given explicitly', async () => {
    const dir = path.join(await mkdtemp(path.join(tmpdir(), 'agent-initiator-e2e-missing-')), 'new-app');
    await init(dir, '--preset', 'typescript,nestjs');
    expect(await readFile(path.join(dir, 'AGENTS.md'), 'utf8')).toContain('**Stack:** TypeScript, NestJS');
  });

  it('refuses scaffolding flags in a non-empty directory', async () => {
    const dir = await copyFixture('express');
    await expect(init(dir, '--framework', 'nextjs')).rejects.toMatchObject({ stderr: expect.stringContaining('is not empty') });
  });

  it('status reports a fresh init as up to date and an edited or outdated file after that', async () => {
    const dir = await copyFixture('fastapi');
    await init(dir);
    const status = () => run('node', [cli, 'status', dir]).then((r) => ({ ...r, code: 0 }), (e: { stdout: string; code: number }) => e);
    const fresh = await status();
    expect(fresh.code).toBe(0);
    expect(fresh.stdout).toMatch(/(\d+) of \1 file\(s\) up to date/);

    // A person edits one rule; another one is made to look like an older template wrote it.
    const rules = path.join(dir, '.agents', 'rules');
    await writeFile(path.join(rules, 'security.md'), `${await readFile(path.join(rules, 'security.md'), 'utf8')}- team note\n`);
    const older = `${await readFile(path.join(rules, 'testing.md'), 'utf8')}old line\n`;
    await writeFile(path.join(rules, 'testing.md'), older);
    const manifestPath = path.join(dir, '.agents', 'agent-initiator.json');
    const manifest = JSON.parse(await readFile(manifestPath, 'utf8')) as { files: Record<string, string> };
    manifest.files['.agents/rules/testing.md'] = `sha256:${createHash('sha256').update(older).digest('hex')}`;
    await writeFile(manifestPath, JSON.stringify(manifest));

    const changed = await status();
    expect(changed.code).toBe(1);
    expect(changed.stdout).toMatch(/edited[^\n]*\n  \.agents\/rules\/security\.md/);
    expect(changed.stdout).toMatch(/outdated[^\n]*\n  \.agents\/rules\/testing\.md\n    git diff --no-index -- /);
  });

  it('init --upgrade updates untouched outdated files, restores missing ones and never touches edited ones', async () => {
    const dir = await copyFixture('fastapi');
    await init(dir);
    const rules = path.join(dir, '.agents', 'rules');
    const read = (p: string) => readFile(path.join(dir, p), 'utf8');
    await writeFile(path.join(rules, 'security.md'), `${await read('.agents/rules/security.md')}- team note\n`);
    const older = `${await read('.agents/rules/testing.md')}old line\n`;
    await writeFile(path.join(rules, 'testing.md'), older);
    const manifestPath = path.join(dir, '.agents', 'agent-initiator.json');
    const manifest = JSON.parse(await read('.agents/agent-initiator.json')) as { files: Record<string, string> };
    manifest.files['.agents/rules/testing.md'] = `sha256:${createHash('sha256').update(older).digest('hex')}`;
    await writeFile(manifestPath, JSON.stringify(manifest));
    await rm(path.join(dir, '.agents', 'skills', 'commit', 'SKILL.md'));

    const dry = await init(dir, '--upgrade', '--dry-run');
    expect(dry.stdout).toContain('Would update 2 file(s)');
    expect(await read('.agents/rules/testing.md')).toBe(older);

    await init(dir, '--upgrade');
    expect(await read('.agents/rules/security.md')).toContain('- team note');
    expect(await read('.agents/rules/testing.md')).not.toContain('old line');
    expect(await read('.agents/skills/commit/SKILL.md')).toContain('name: commit');
    const upgraded = JSON.parse(await read('.agents/agent-initiator.json')) as { upgradedAt?: string };
    expect(upgraded.upgradedAt).toMatch(/^\d{4}-\d{2}-\d{2}$/);

    const after = await run('node', [cli, 'status', dir]);
    expect(after.stdout).toMatch(/edited[^\n]*\n  \.agents\/rules\/security\.md/);
    expect(after.stdout).not.toContain('outdated');
  });

  it('leaves the wiki to the team: a deleted or rewritten page is neither reported nor restored', async () => {
    const dir = await copyFixture('fastapi');
    await init(dir);
    await rm(path.join(dir, 'docs', 'wiki', 'en', 'faq.md'));
    await writeFile(path.join(dir, 'docs', 'wiki', 'en', 'overview.md'), '# Our overview\n');

    const status = await run('node', [cli, 'status', dir]);
    expect(status.stdout).toContain('Not compared: docs/wiki/');
    expect(status.stdout).not.toContain('docs/wiki/en/faq.md');

    await init(dir, '--upgrade');
    await expect(readFile(path.join(dir, 'docs', 'wiki', 'en', 'faq.md'), 'utf8')).rejects.toThrow();
    expect(await readFile(path.join(dir, 'docs', 'wiki', 'en', 'overview.md'), 'utf8')).toBe('# Our overview\n');
  });
});

