/** Tests the init manifest (what was generated, by which version) and how an earlier init is detected. */
import { createHash } from 'node:crypto';
import { mkdir, mkdtemp, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { describe, expect, it } from 'vitest';
import { detectInitState, readManifest } from '../src/detect/initialised.js';
import { contentHash, MANIFEST_PATH, renderManifest, upgradeManifest, type InitManifest } from '../src/render/manifest.js';

describe('renderManifest', () => {
  it('records version, date, presets, tools and a sha256 of every written file', () => {
    const file = renderManifest({
      version: '0.1.0',
      date: '2026-10-03',
      presets: ['base', 'python'],
      tools: ['rtk'],
      written: [{ path: 'AGENTS.md', content: '# AGENTS.md\n' }],
    });
    expect(file.path).toBe('.agents/agent-initiator.json');
    const manifest = JSON.parse(file.content) as InitManifest;
    expect(manifest).toEqual({
      generator: 'agent-initiator',
      version: '0.1.0',
      generatedAt: '2026-10-03',
      presets: ['base', 'python'],
      tools: ['rtk'],
      files: { 'AGENTS.md': `sha256:${createHash('sha256').update('# AGENTS.md\n').digest('hex')}` },
    });
  });

  it('hashes the exact UTF-8 content, so any edit changes the hash', () => {
    expect(contentHash('a — b')).not.toBe(contentHash('a - b'));
    expect(contentHash('x')).toBe(contentHash('x'));
  });
});

describe('upgradeManifest', () => {
  it('records the new version and upgrade date and rehashes only the files the upgrade wrote', () => {
    const before: InitManifest = {
      generator: 'agent-initiator', version: '0.1.0', generatedAt: '2026-10-01', presets: ['base'], tools: [],
      files: { 'a.md': contentHash('a'), 'b.md': contentHash('b') },
    };
    const after = JSON.parse(upgradeManifest(before, '0.2.0', '2026-10-03', [{ path: 'b.md', content: 'B' }, { path: 'c.md', content: 'c' }]).content) as InitManifest;
    expect(after).toEqual({ ...before, version: '0.2.0', upgradedAt: '2026-10-03', files: { 'a.md': contentHash('a'), 'b.md': contentHash('B'), 'c.md': contentHash('c') } });
  });
});

describe('detectInitState', () => {
  /** A temp repository with the given files. */
  async function repo(files: Record<string, string>): Promise<string> {
    const dir = await mkdtemp(path.join(tmpdir(), 'agent-initiator-state-'));
    for (const [file, content] of Object.entries(files)) {
      await mkdir(path.dirname(path.join(dir, file)), { recursive: true });
      await writeFile(path.join(dir, file), content);
    }
    return dir;
  }

  it('reads version and date from the manifest', async () => {
    const dir = await repo({ [MANIFEST_PATH]: JSON.stringify({ version: '0.2.0', generatedAt: '2026-10-03', presets: [], tools: [], files: {} }) });
    expect(await detectInitState(dir)).toEqual({ kind: 'manifest', version: '0.2.0', generatedAt: '2026-10-03' });
  });

  it('recognises an earlier init by the AGENTS.md marker when there is no manifest', async () => {
    const dir = await repo({ 'AGENTS.md': '# AGENTS.md\n\n<!-- Generated by agent-initiator. Safe to edit -->\n' });
    expect(await detectInitState(dir)).toEqual({ kind: 'legacy' });
  });

  it('ignores a manifest without the expected fields, and reports none for an untouched repo', async () => {
    expect(await detectInitState(await repo({ [MANIFEST_PATH]: '{"version": 1}' }))).toEqual({ kind: 'none' });
    const base = { version: '1.0.0', generatedAt: '2026-10-03', presets: [], tools: [] };
    const upgraded = await readManifest(await repo({ [MANIFEST_PATH]: JSON.stringify({ ...base, files: {}, upgradedAt: '2026-10-04' }) }));
    expect(upgraded?.upgradedAt).toBe('2026-10-04');
    for (const broken of [{ ...base, files: { 'AGENTS.md': 1 } }, { ...base, files: [] }, { ...base, tools: [1], files: {} }]) {
      expect(await readManifest(await repo({ [MANIFEST_PATH]: JSON.stringify(broken) }))).toBeNull();
    }
    expect(await detectInitState(await repo({ 'AGENTS.md': '# My own notes\n' }))).toEqual({ kind: 'none' });
  });
});
