import path from 'node:path';
import { readJson, readText } from '../fs-utils.js';
import { MANIFEST_PATH, type InitManifest } from '../render/manifest.js';

/** Earlier versions left only this marker in AGENTS.md, without a manifest. */
const LEGACY_MARKER = 'Generated by agent-initiator';

/** Whether, and by which version, agent-initiator already initialised a repository. */
export type InitState =
  | { kind: 'manifest'; version: string; generatedAt: string }
  | { kind: 'legacy' }
  | { kind: 'none' };

/** True when every value is a string, e.g. the manifest's path → hash map. */
function isStringRecord(value: unknown): value is Record<string, string> {
  return typeof value === 'object' && value !== null && !Array.isArray(value) && Object.values(value).every((v) => typeof v === 'string');
}

/** True when every item is a string, e.g. the manifest's presets and tools lists. */
function isStringList(value: unknown): value is string[] {
  return Array.isArray(value) && value.every((v) => typeof v === 'string');
}

/**
 * Reads the manifest an earlier init wrote. It is a file in the user's repository, so every field is checked.
 * @param root - Repository root.
 * @returns The manifest, or null when there is none or its fields are not what init writes.
 */
export async function readManifest(root: string): Promise<InitManifest | null> {
  const data = await readJson<Record<string, unknown>>(path.join(root, MANIFEST_PATH));
  if (!data || typeof data.version !== 'string' || typeof data.generatedAt !== 'string') return null;
  if (!isStringList(data.presets) || !isStringList(data.tools) || !isStringRecord(data.files)) return null;
  const manifest: InitManifest = { generator: 'agent-initiator', version: data.version, generatedAt: data.generatedAt, presets: data.presets, tools: data.tools, files: data.files };
  return typeof data.upgradedAt === 'string' ? { ...manifest, upgradedAt: data.upgradedAt } : manifest;
}

/**
 * Finds the trace of an earlier init: the manifest, or else the marker that versions before the manifest wrote in
 * AGENTS.md. The manifest is a file in the user's repository, so its fields are checked before they are trusted.
 * @param root - Repository root.
 */
export async function detectInitState(root: string): Promise<InitState> {
  const manifest = await readManifest(root);
  if (manifest) return { kind: 'manifest', version: manifest.version, generatedAt: manifest.generatedAt };
  const agentsMd = await readText(path.join(root, 'AGENTS.md'));
  return agentsMd?.includes(LEGACY_MARKER) ? { kind: 'legacy' } : { kind: 'none' };
}
