import path from 'node:path';
import { readJson, readText } from '../fs-utils.js';
import { MANIFEST_PATH } from '../render/manifest.js';

/** Earlier versions left only this marker in AGENTS.md, without a manifest. */
const LEGACY_MARKER = 'Generated by agent-initiator';

/** Whether, and by which version, agent-initiator already initialised a repository. */
export type InitState =
  | { kind: 'manifest'; version: string; generatedAt: string }
  | { kind: 'legacy' }
  | { kind: 'none' };

/**
 * Finds the trace of an earlier init: the manifest, or else the marker that versions before the manifest wrote in
 * AGENTS.md. The manifest is a file in the user's repository, so its fields are checked before they are trusted.
 * @param root - Repository root.
 */
export async function detectInitState(root: string): Promise<InitState> {
  const manifest = await readJson<Record<string, unknown>>(path.join(root, MANIFEST_PATH));
  if (manifest && typeof manifest.version === 'string' && typeof manifest.generatedAt === 'string') {
    return { kind: 'manifest', version: manifest.version, generatedAt: manifest.generatedAt };
  }
  const agentsMd = await readText(path.join(root, 'AGENTS.md'));
  return agentsMd?.includes(LEGACY_MARKER) ? { kind: 'legacy' } : { kind: 'none' };
}
