import path from 'node:path';
import { getTool } from '../tooling.js';
import type { ProjectKind, RuleFile, Skill } from '../types.js';
import type { Command } from './commands.js';

export const GENERATED_NOTE = '<!-- Generated by agent-initiator. Safe to edit: re-running never overwrites existing files. -->';

export interface PackageSummary {
  path: string;
  name: string;
  stack: string;
}

export interface RootAgentsInput {
  projectName: string;
  kind: ProjectKind;
  stack: string;
  packageManager?: string;
  monorepoName?: string;
  packages: PackageSummary[];
  commands: Command[];
  tooling: string[];
  docs: string[];
  agentsMdBlocks: string[];
  conventions: string[];
  must: string[];
  never: string[];
  rules: Array<RuleFile & { scope?: string }>;
  skills: Skill[];
}

export interface PackageAgentsInput {
  pkg: PackageSummary;
  language: string;
  commands: Command[];
  rootCommand?: string;
  docs: string[];
  agentsMdBlocks: string[];
  conventions: string[];
  must: string[];
  never: string[];
  rules: RuleFile[];
  skills: Skill[];
}

const bullets = (items: string[]) => items.map((item) => `- ${item}`);

function commandTable(commands: Command[]): string[] {
  return ['| Task | Command |', '|------|---------|', ...commands.map((c) => `| ${c.task} | \`${c.command}\` |`)];
}

function ruleScope(rule: RuleFile & { scope?: string }): string {
  if (rule.scope) return rule.scope;
  if (rule.alwaysApply || rule.globs.length === 0) return 'always';
  return rule.globs.map((g) => `\`${g}\``).join(', ');
}

function rulesSection(rules: Array<RuleFile & { scope?: string }>, base: string): string[] {
  if (rules.length === 0) return [];
  return [
    '## Rules',
    '',
    'Read the matching rule before working in its area. `always` rules apply to every task.',
    '',
    '| Rule | Applies | Summary |',
    '|------|---------|---------|',
    ...rules.map((r) => `| [${r.file.replace(/\.md$/, '')}](${base}.agents/rules/${r.file}) | ${ruleScope(r)} | ${r.description} |`),
    '',
  ];
}

function skillsSection(skills: Skill[], base: string): string[] {
  if (skills.length === 0) return [];
  return [
    '## Skills',
    '',
    'Skills live in `.agents/skills/` (mirrored to `.claude/skills/` for Claude Code). Load a skill when its description matches the task.',
    '',
    ...skills.map((s) => `- [${s.name}](${base}.agents/skills/${s.name}/SKILL.md) — ${s.description}`),
    '',
  ];
}

function docsSection(docs: string[]): string[] {
  if (docs.length === 0) return [];
  return [
    '## Framework docs',
    '',
    'Your training data may be outdated. Before using a framework API, read the version-matched source below and heed deprecation notices.',
    '',
    ...bullets(docs),
    '',
  ];
}

/** Verbatim blocks owned by a framework (e.g. the Next.js managed block that `next dev` checks for). */
function blocksSection(blocks: string[]): string[] {
  return blocks.flatMap((block) => [block, '']);
}

function constraintsSection(must: string[], never: string[]): string[] {
  if (must.length === 0 && never.length === 0) return [];
  const lines = ['## Constraints', ''];
  if (must.length > 0) lines.push('### MUST', ...bullets(must), '');
  if (never.length > 0) lines.push('### NEVER', ...bullets(never), '');
  return lines;
}

function toolingSection(toolIds: string[]): string[] {
  if (toolIds.length === 0) return [];
  const lines = [
    '## Required tooling',
    '',
    'Mandatory for every contributor and agent. Install once per machine (`npx agent-initiator doctor` checks them).',
    '',
  ];
  for (const tool of toolIds.map(getTool)) {
    lines.push(`### [${tool.name}](${tool.url})`, tool.purpose, '', `**Use:** ${tool.usage}`, '', '```bash', ...tool.install, '```', '');
  }
  return lines;
}

function dodSection(commands: Command[], hasPackages: boolean): string[] {
  const find = (task: string) => commands.find((c) => c.task === task)?.command;
  const missing = (task: string) => `_no \`${task}\` command configured yet — add one before relying on this step_`;
  const perPackage = commands.length === 0 && hasPackages;
  // Multi-package repos without root commands point to each package's own AGENTS.md.
  const step = (task: string) => {
    if (perPackage) return `run each affected package's \`${task}\` command (see its AGENTS.md)`;
    const command = find(task);
    return command ? `\`${command}\`` : missing(task);
  };
  return [
    '## Definition of Done',
    '',
    'A task is done only when every step passes (use the `definition-of-done` skill):',
    '',
    '1. Code follows the conventions, constraints and rules in this file, and the `self-review` skill found nothing left to fix.',
    `2. Unit tests pass with coverage ≥ 80% on changed code: ${step('test')}`,
    `3. Build succeeds: ${step('build')}`,
    `4. Dependencies audited when they changed: ${step('audit')}`,
    '5. Wiki updated in both `docs/wiki/en/` and `docs/wiki/id/`: the page of the topic you worked on (create it if missing), related pages, `index.md` and a new `log.md` entry — a log entry alone is not enough; ADR for architecture decisions.',
    '',
  ];
}

/** Renders the root AGENTS.md: the single entry point every agent reads first. */
export function renderRootAgentsMd(input: RootAgentsInput): string {
  const overview = [
    `- **Type:** ${input.kind}`,
    `- **Stack:** ${input.stack || 'not detected — describe it here'}`,
    ...(input.packageManager ? [`- **Package manager:** ${input.packageManager}`] : []),
    ...(input.monorepoName ? [`- **Monorepo tool:** ${input.monorepoName}`] : []),
  ];

  const packages =
    input.packages.length > 0
      ? [
          '',
          '### Packages',
          '',
          'Each package has its own `AGENTS.md` with stack-specific commands and rules (the nearest `AGENTS.md` wins).',
          '',
          '| Path | Name | Stack |',
          '|------|------|-------|',
          ...input.packages.map((p) => `| [\`${p.path}\`](${p.path}/AGENTS.md) | ${p.name} | ${p.stack} |`),
        ]
      : [];

  const commands =
    input.commands.length > 0
      ? ['## Commands', '', 'Run from the repo root. Keep the `rtk` prefix.', '', ...commandTable(input.commands), '']
      : input.packages.length > 0
        ? ['## Commands', '', "Commands are per package — see each package's `AGENTS.md`.", '']
        : [];

  return [
    '# AGENTS.md',
    '',
    GENERATED_NOTE,
    '',
    `Instructions for AI coding assistants working in **${input.projectName}**. Read this file first, then the rules and skills it links to.`,
    '',
    ...blocksSection(input.agentsMdBlocks),
    '## Project overview',
    '',
    ...overview,
    ...packages,
    '',
    ...commands,
    ...docsSection(input.docs),
    ...toolingSection(input.tooling),
    ...constraintsSection(input.must, input.never),
    ...dodSection(input.commands, input.packages.length > 0),
    ...(input.conventions.length > 0 ? ['## Conventions', '', ...bullets(input.conventions), ''] : []),
    ...rulesSection(input.rules, ''),
    ...skillsSection(input.skills, ''),
  ].join('\n');
}

/** Renders a nested AGENTS.md for one package of a multi-package repo. */
export function renderPackageAgentsMd(input: PackageAgentsInput): string {
  // Links point back to the shared .agents/ folder at the repo root.
  const up = `${path.posix.relative(input.pkg.path, '.')}/`;
  return [
    `# AGENTS.md — ${input.pkg.name}`,
    '',
    GENERATED_NOTE,
    '',
    `Package-specific instructions for \`${input.pkg.path}\`. The [root AGENTS.md](${up}AGENTS.md) (tooling, constraints, Definition of Done, shared rules) still applies.`,
    '',
    ...blocksSection(input.agentsMdBlocks),
    '## Overview',
    '',
    `- **Stack:** ${input.pkg.stack}`,
    `- **Language:** ${input.language}`,
    '',
    ...(input.commands.length > 0
      ? [
          '## Commands',
          '',
          `Run inside \`${input.pkg.path}\`. Keep the \`rtk\` prefix.`,
          '',
          ...commandTable(input.commands),
          ...(input.rootCommand ? ['', `From the repo root: \`${input.rootCommand}\``] : []),
          '',
        ]
      : []),
    ...docsSection(input.docs),
    ...constraintsSection(input.must, input.never),
    ...(input.conventions.length > 0 ? ['## Conventions', '', ...bullets(input.conventions), ''] : []),
    ...rulesSection(input.rules, up),
    ...skillsSection(input.skills, up),
  ].join('\n');
}
