import path from 'node:path';
import { getTool } from '../tooling.js';
import type { ProjectKind, RuleFile, Skill } from '../types.js';
import type { Command } from './commands.js';

export const GENERATED_NOTE = '<!-- Generated by agent-initiator. Safe to edit: re-running never overwrites existing files. -->';

export interface PackageSummary {
  path: string;
  name: string;
  stack: string;
}

export interface RootAgentsInput {
  projectName: string;
  kind: ProjectKind;
  stack: string;
  packageManager?: string;
  monorepoName?: string;
  packages: PackageSummary[];
  commands: Command[];
  tooling: string[];
  docs: string[];
  agentsMdBlocks: string[];
  conventions: string[];
  must: string[];
  never: string[];
  rules: Array<RuleFile & { scope?: string }>;
  skills: Skill[];
}

export interface PackageAgentsInput {
  pkg: PackageSummary;
  language: string;
  commands: Command[];
  /** Whether the commands carry the rtk prefix (rtk is installed). */
  rtk: boolean;
  rootCommand?: string;
  docs: string[];
  agentsMdBlocks: string[];
  conventions: string[];
  must: string[];
  never: string[];
  rules: RuleFile[];
  skills: Skill[];
}

const bullets = (items: string[]) => items.map((item) => `- ${item}`);

function commandTable(commands: Command[]): string[] {
  return ['| Task | Command |', '|------|---------|', ...commands.map((c) => `| ${c.task} | \`${c.command}\` |`)];
}

/** Markdown link to a rule file, named after the file. */
const ruleLink = (rule: RuleFile, base: string) => `[${rule.file.replace(/\.md$/, '')}](${base}.agents/rules/${rule.file})`;

/** When a rule applies: `always`, a package scope, its file globs, or on demand (described by its summary). */
function ruleScope(rule: RuleFile & { scope?: string }): string {
  if (rule.scope) return rule.scope;
  if (rule.alwaysApply) return 'always';
  if (rule.globs.length > 0) return rule.globs.map((g) => `\`${g}\``).join(', ');
  return `on demand: ${rule.description}`;
}

/**
 * Lists the rules compactly: `always` rules on one line (they are read for every task anyway, so a summary adds
 * nothing), then each scoped or on-demand rule with when it applies. Each rule file carries its own description.
 */
function rulesSection(rules: Array<RuleFile & { scope?: string }>, base: string): string[] {
  if (rules.length === 0) return [];
  const always = rules.filter((r) => ruleScope(r) === 'always');
  const scoped = rules.filter((r) => ruleScope(r) !== 'always');
  return [
    '## Rules',
    '',
    'Read every `always` rule before you start, a scoped rule before you change matching files, and an on-demand rule when your task matches its description.',
    '',
    ...(always.length > 0 ? [`- **Always:** ${always.map((r) => ruleLink(r, base)).join(', ')}`] : []),
    ...scoped.map((r) => `- ${ruleLink(r, base)} — ${ruleScope(r)}`),
    '',
  ];
}

/**
 * Lists the skills by name only. Agents already read each skill's description from `.agents/skills/` or
 * `.claude/skills/` to decide when to load it, so repeating the descriptions here only costs tokens.
 */
function skillsSection(skills: Skill[], base: string): string[] {
  if (skills.length === 0) return [];
  return [
    '## Skills',
    '',
    'In `.agents/skills/` (mirrored to `.claude/skills/` for Claude Code). Load a skill when its description matches the task:',
    skills.map((s) => `[${s.name}](${base}.agents/skills/${s.name}/SKILL.md)`).join(', '),
    '',
  ];
}

function docsSection(docs: string[]): string[] {
  if (docs.length === 0) return [];
  return [
    '## Framework docs',
    '',
    'Your training data may be outdated. Before using a framework API, read the version-matched source below and heed deprecation notices.',
    '',
    ...bullets(docs),
    '',
  ];
}

/** Verbatim blocks owned by a framework (e.g. the Next.js managed block that `next dev` checks for). */
function blocksSection(blocks: string[]): string[] {
  return blocks.flatMap((block) => [block, '']);
}

function constraintsSection(must: string[], never: string[]): string[] {
  if (must.length === 0 && never.length === 0) return [];
  const lines = ['## Constraints', ''];
  if (must.length > 0) lines.push('### MUST', ...bullets(must), '');
  if (never.length > 0) lines.push('### NEVER', ...bullets(never), '');
  return lines;
}

/**
 * Tells AI agents where to learn about the project before reading code, in the cheapest order:
 * the English wiki (index → one page), then graphify for structure questions (when it is a required tool), then grep.
 * @param toolIds - Required tool ids; the graphify lines are shown only when graphify is one of them.
 * @returns Markdown lines for the "Project knowledge" section.
 */
function projectKnowledgeSection(toolIds: string[]): string[] {
  return [
    '## Project knowledge',
    '',
    'Before exploring the code, read the wiki: `docs/wiki/en/index.md` lists every page and has a task → page table. Open only the pages your task needs.',
    '',
    '- AI agents read the English pages only; `docs/wiki/id/` is the same content in Indonesian.',
    '- Skip `docs/wiki/*/log.md` unless you are investigating history.',
    ...(toolIds.includes('graphify')
      ? [
          '- For structure and impact questions, ask graphify with a symbol name: `graphify affected "<symbol>"`, `graphify path "<A>" "<B>"`, `graphify explain "<symbol>"` (add `--budget <tokens>` to cap the answer).',
          '- No `graphify-out/` yet? Build it first: `graphify update .` (code only, no tokens).',
          '- If `graphify hook status` shows missing hooks (e.g. in a fresh clone), run `graphify hook install` once so the graph is rebuilt after every commit.',
        ]
      : []),
    `- Use grep only for what the wiki${toolIds.includes('graphify') ? ' and graphify do' : ' does'} not answer.`,
    '',
  ];
}

/**
 * How to use each required tool, one line each; install steps live in the required-tooling rule.
 * AGENTS.md is generated on one machine but read on others, so it also says what to do when a tool is missing there:
 * check once, then skip that tool's instructions, instead of failing and retrying on every command.
 */
function toolingSection(toolIds: string[]): string[] {
  if (toolIds.length === 0) return [];
  const tools = toolIds.map(getTool);
  const bins = tools.flatMap((tool) => tool.check.bins ?? []);
  const missing = [
    bins.length > 0 ? `Check once per session which are installed (\`command -v ${bins.join(' ')}\`).` : '',
    'If a tool is missing on your machine, skip its instructions instead of retrying',
    toolIds.includes('rtk') ? ': without rtk, run each command without its `rtk`, `rtk test`, `rtk err` or `rtk proxy` prefix (`rtk test pnpm run test` → `pnpm run test`).' : '.',
  ].join(bins.length > 0 ? ' ' : '');
  return [
    '## Required tooling',
    '',
    'These tools were installed when this file was generated, so use them on every task. Install steps: [required-tooling](.agents/rules/required-tooling.md); `npx agent-initiator doctor` shows what this machine has.',
    missing.replace(' :', ':').trim(),
    '',
    ...tools.map((tool) => `- **${tool.name}** — ${tool.usage}`),
    '',
  ];
}

/**
 * The Definition of Done for AGENTS.md, with the real commands for each step.
 * Coverage uses the project's coverage command when it has one; otherwise the step says what to do instead, because
 * agents otherwise get stuck on a check they cannot run (seen in the cross-model evaluation).
 */
function dodSection(commands: Command[], hasPackages: boolean): string[] {
  const find = (task: string) => commands.find((c) => c.task === task)?.command;
  const missing = (task: string) => `_no \`${task}\` command configured yet — add one before relying on this step_`;
  const perPackage = commands.length === 0 && hasPackages;
  // Multi-package repos without root commands point to each package's own AGENTS.md.
  const step = (task: string) => {
    if (perPackage) return `run each affected package's \`${task}\` command (see its AGENTS.md)`;
    const command = find(task);
    return command ? `\`${command}\`` : missing(task);
  };
  return [
    '## Definition of Done',
    '',
    'A task is done only when every step passes (use the `definition-of-done` skill):',
    '',
    '1. Code follows the conventions, constraints and rules in this file, and the `self-review` skill found nothing left to fix.',
    find('coverage') || perPackage
      ? `2. Unit tests pass with coverage ≥ 80% on changed code: ${step(find('coverage') ? 'coverage' : 'test')}`
      : `2. Unit tests pass: ${step('test')}. Coverage ≥ 80% on changed code: no coverage command yet, so use the runner's coverage option or report it as not measured (ask before adding a dependency).`,
    `3. Build succeeds: ${step('build')}`,
    `4. Dependencies audited when they changed: ${step('audit')}`,
    '5. Wiki updated in both `docs/wiki/en/` and `docs/wiki/id/`: the page of the topic you worked on (create it if missing), related pages, `index.md` and a new `log.md` entry — a log entry alone is not enough; ADR for architecture decisions.',
    '',
  ];
}

/** Renders the root AGENTS.md: the single entry point every agent reads first. */
export function renderRootAgentsMd(input: RootAgentsInput): string {
  const overview = [
    `- **Type:** ${input.kind}`,
    `- **Stack:** ${input.stack || 'not detected — describe it here'}`,
    ...(input.packageManager ? [`- **Package manager:** ${input.packageManager}`] : []),
    ...(input.monorepoName ? [`- **Monorepo tool:** ${input.monorepoName}`] : []),
  ];

  const packages =
    input.packages.length > 0
      ? [
          '',
          '### Packages',
          '',
          'Each package has its own `AGENTS.md` with stack-specific commands and rules (the nearest `AGENTS.md` wins).',
          '',
          '| Path | Name | Stack |',
          '|------|------|-------|',
          ...input.packages.map((p) => `| [\`${p.path}\`](${p.path}/AGENTS.md) | ${p.name} | ${p.stack} |`),
        ]
      : [];

  const commands =
    input.commands.length > 0
      ? ['## Commands', '', `Run from the repo root.${input.tooling.includes('rtk') ? ' Keep the `rtk` prefix.' : ''}`, '', ...commandTable(input.commands), '']
      : input.packages.length > 0
        ? ['## Commands', '', "Commands are per package — see each package's `AGENTS.md`.", '']
        : [];

  return [
    '# AGENTS.md',
    '',
    GENERATED_NOTE,
    '',
    `Instructions for AI coding assistants working in **${input.projectName}**. Read this file first, then the rules and skills it links to.`,
    '',
    ...blocksSection(input.agentsMdBlocks),
    '## Project overview',
    '',
    ...overview,
    ...packages,
    '',
    ...commands,
    ...projectKnowledgeSection(input.tooling),
    ...docsSection(input.docs),
    ...toolingSection(input.tooling),
    ...constraintsSection(input.must, input.never),
    ...dodSection(input.commands, input.packages.length > 0),
    ...(input.conventions.length > 0 ? ['## Conventions', '', ...bullets(input.conventions), ''] : []),
    ...rulesSection(input.rules, ''),
    ...skillsSection(input.skills, ''),
  ].join('\n');
}

/** Renders a nested AGENTS.md for one package of a multi-package repo. */
export function renderPackageAgentsMd(input: PackageAgentsInput): string {
  // Links point back to the shared .agents/ folder at the repo root.
  const up = `${path.posix.relative(input.pkg.path, '.')}/`;
  return [
    `# AGENTS.md — ${input.pkg.name}`,
    '',
    GENERATED_NOTE,
    '',
    `Package-specific instructions for \`${input.pkg.path}\`. The [root AGENTS.md](${up}AGENTS.md) (project knowledge, tooling, constraints, Definition of Done, shared rules) still applies: read the English wiki in \`${up}docs/wiki/en/\` before exploring the code.`,
    '',
    ...blocksSection(input.agentsMdBlocks),
    '## Overview',
    '',
    `- **Stack:** ${input.pkg.stack}`,
    `- **Language:** ${input.language}`,
    '',
    ...(input.commands.length > 0
      ? [
          '## Commands',
          '',
          `Run inside \`${input.pkg.path}\`.${input.rtk ? ' Keep the `rtk` prefix.' : ''}`,
          '',
          ...commandTable(input.commands),
          ...(input.rootCommand ? ['', `From the repo root: \`${input.rootCommand}\``] : []),
          '',
        ]
      : []),
    ...docsSection(input.docs),
    ...constraintsSection(input.must, input.never),
    ...(input.conventions.length > 0 ? ['## Conventions', '', ...bullets(input.conventions), ''] : []),
    ...rulesSection(input.rules, up),
    ...skillsSection(input.skills, up),
  ].join('\n');
}
