import type { CiJob } from '../types.js';

// Action versions checked against each action's latest release (2026-10). Update them together.
const ACTIONS = {
  checkout: 'actions/checkout@v7',
  node: 'actions/setup-node@v7',
  bun: 'oven-sh/setup-bun@v2',
  uv: 'astral-sh/setup-uv@v10',
  python: 'actions/setup-python@v7',
  go: 'actions/setup-go@v7',
};

/** YAML lines that put the language and package manager on the runner. */
function setupSteps(job: CiJob): string[] {
  const pm = job.packageManager;
  if (pm === 'bun') return [`      - uses: ${ACTIONS.bun}`];
  if (job.language === 'typescript' || job.language === 'javascript') {
    const lines = [`      - uses: ${ACTIONS.node}`, '        with:', '          node-version: lts/*'];
    // corepack installs the pnpm/yarn version from the packageManager field in package.json (or a recent one).
    // It is installed from npm because newer Node.js versions no longer ship it.
    if (pm === 'pnpm' || pm === 'yarn') lines.push('      - run: npm install -g corepack && corepack enable');
    return lines;
  }
  if (pm === 'uv') return [`      - uses: ${ACTIONS.uv}`];
  if (job.language === 'python') {
    const lines = [`      - uses: ${ACTIONS.python}`, '        with:', "          python-version: '3.x'"];
    if (pm === 'poetry') lines.push('      - run: pipx install poetry');
    return lines;
  }
  if (job.language === 'go') {
    return [`      - uses: ${ACTIONS.go}`, '        with:', `          go-version-file: ${JSON.stringify(job.path === '.' ? 'go.mod' : `${job.path}/go.mod`)}`];
  }
  return [];
}

/** Job id GitHub accepts (letters, digits, `-`, `_`): "ci" for the root package, else the folder path. */
function jobId(path: string): string {
  return path === '.' ? 'ci' : path.replace(/[^A-Za-z0-9_-]/g, '-');
}

/** YAML lines for one job. Commands are JSON strings, which are valid YAML, so special characters stay safe. */
function jobLines(job: CiJob): string[] {
  const lines = [`  ${jobId(job.path)}:`, `    name: ${JSON.stringify(job.path === '.' ? 'checks' : `checks (${job.path})`)}`, '    runs-on: ubuntu-latest'];
  if (job.path !== '.') lines.push('    defaults:', '      run:', `        working-directory: ${JSON.stringify(job.path)}`);
  lines.push('    steps:', `      - uses: ${ACTIONS.checkout}`, ...setupSteps(job));
  lines.push('      - name: install', `        run: ${JSON.stringify(job.install)}`);
  if (job.installAtRoot && job.path !== '.') lines.push('        working-directory: .');
  for (const step of job.steps) lines.push(`      - name: ${step.name}`, `        run: ${JSON.stringify(step.run)}`);
  return lines;
}

/**
 * Renders .github/workflows/ci.yml: on every push to the main branch and every pull request, each package
 * installs from its lockfile and runs lint → typecheck → test → build → audit. Any failing step fails the check.
 * @param jobs - One job per package that has at least one check.
 * @returns The YAML text.
 */
export function renderGithubCi(jobs: CiJob[]): string {
  const lines = [
    '# Quality gates for every pull request, generated by agent-initiator.',
    '# Same commands as AGENTS.md → Commands. Never weaken or skip a step to get a change merged; fix the cause.',
    'name: ci',
    '',
    'on:',
    '  push:',
    '    branches: [main, master]',
    '  pull_request:',
    '',
    '# Least privilege: the checks only need to read the code.',
    'permissions:',
    '  contents: read',
    '',
    'env:',
    // Without this, corepack may wait for a "download pnpm?" answer that never comes on CI.
    "  COREPACK_ENABLE_DOWNLOAD_PROMPT: '0'",
    '',
    'jobs:',
  ];
  jobs.forEach((job, index) => {
    if (index > 0) lines.push('');
    lines.push(...jobLines(job));
  });
  return `${lines.join('\n')}\n`;
}
