import type { CiJob } from '../types.js';

// Official Docker images per toolchain; the tags follow the newest stable release (checked 2026-10).
// golang:1 is always a recent Go, which builds modules that ask for an older one.
const IMAGES = { node: 'node:lts', bun: 'oven/bun:1', python: 'python:3', go: 'golang:1' };

/** The image a job runs in, picked from its language and package manager. */
function image(job: CiJob): string {
  if (job.packageManager === 'bun') return IMAGES.bun;
  if (job.language === 'python') return IMAGES.python;
  if (job.language === 'go') return IMAGES.go;
  return IMAGES.node;
}

/** Commands that put the package manager in the image, when the image does not ship it. */
function setupCommands(job: CiJob): string[] {
  // corepack installs the pnpm/yarn version from package.json → packageManager; newer Node.js no longer ships it.
  if (job.packageManager === 'pnpm' || job.packageManager === 'yarn') return ['npm install -g corepack && corepack enable'];
  if (job.packageManager === 'uv') return ['pip install uv'];
  if (job.packageManager === 'poetry') return ['pip install poetry'];
  return [];
}

/**
 * The script of one job: install, then the checks, all in the package folder. Workspace packages install
 * from the repo root first, where the shared lockfile is.
 */
function scriptCommands(job: CiJob): string[] {
  const enterPackage = job.path === '.' ? [] : [`cd ${JSON.stringify(job.path)}`];
  const install = job.installAtRoot ? [job.install, ...enterPackage] : [...enterPackage, job.install];
  return [...install, ...job.steps.map((step) => step.run)];
}

/** YAML lines for one job. Commands are JSON strings, which are valid YAML, so special characters stay safe. */
function jobLines(job: CiJob): string[] {
  const lines = [`${JSON.stringify(job.path === '.' ? 'checks' : `checks (${job.path})`)}:`, `  image: ${image(job)}`];
  const setup = setupCommands(job);
  if (setup.length > 0) lines.push('  before_script:', ...setup.map((command) => `    - ${JSON.stringify(command)}`));
  lines.push('  script:', ...scriptCommands(job).map((command) => `    - ${JSON.stringify(command)}`));
  return lines;
}

// Merge requests only: compares the MR's commits with its base. allow_failure shows a missing wiki update
// as a warning ("passed with warnings") instead of blocking the merge. alpine/git is a small image with git and sh.
const WIKI_JOB = [
  '"wiki check (warning only)":',
  '  image:',
  '    name: alpine/git',
  '    entrypoint: [""]',
  '  rules:',
  '    - if: $CI_PIPELINE_SOURCE == "merge_request_event"',
  '  allow_failure: true',
  '  variables:',
  '    GIT_DEPTH: "0"',
  '  script:',
  `    - ${JSON.stringify('sh .lefthook/pre-push/check-wiki.sh --range "$CI_MERGE_REQUEST_DIFF_BASE_SHA" "$CI_COMMIT_SHA"')}`,
];

/**
 * Renders .gitlab-ci.yml: for every merge request and every push to the default branch, each package installs
 * from its lockfile and runs lint → typecheck → test → build → audit. Any failing command fails the job.
 * Merge requests also get a wiki check that only warns.
 * @param jobs - One job per package that has at least one check.
 * @returns The YAML text.
 */
export function renderGitlabCi(jobs: CiJob[]): string {
  const lines = [
    '# Quality gates for every merge request, generated by agent-initiator.',
    '# Same commands as AGENTS.md → Commands. Never weaken or skip a step to get a change merged; fix the cause.',
    '',
    'workflow:',
    '  rules:',
    '    - if: $CI_PIPELINE_SOURCE == "merge_request_event"',
    '    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH',
    '',
    'variables:',
    // Without this, corepack may wait for a "download pnpm?" answer that never comes on CI.
    '  COREPACK_ENABLE_DOWNLOAD_PROMPT: "0"',
  ];
  for (const job of jobs) lines.push('', ...jobLines(job));
  lines.push('', ...WIKI_JOB);
  return `${lines.join('\n')}\n`;
}
