/** What the generated lefthook.yml should contain. */
export interface LefthookOptions {
  /** Rebuild the graphify code graph after each commit (graphify is a required tool). */
  graphify: boolean;
}

/**
 * Renders lefthook.yml: git hooks that work for every language.
 * - commit-msg runs `.lefthook/commit-msg/check-message.sh` (format `type(#n|TASK-n): subject`, no attribution trailers).
 * - post-commit rebuilds the graphify graph. lefthook replaces existing git hooks, so graphify's own post-commit
 *   hook would stop running; listing it here keeps the graph current.
 * @param options - Which optional hooks to include.
 * @returns The YAML text.
 */
export function renderLefthookConfig(options: LefthookOptions): string {
  const lines = [
    '# Git hooks for every language, managed by lefthook (https://github.com/evilmartians/lefthook).',
    '# Generated by agent-initiator. Activate once per clone with: lefthook install',
    '# Never bypass these hooks with --no-verify; fix what they report instead.',
    '',
    'commit-msg:',
    '  scripts:',
    '    "check-message.sh":',
    '      runner: sh',
  ];
  if (options.graphify) {
    lines.push(
      '',
      'post-commit:',
      '  commands:',
      '    graphify:',
      '      # Keeps the code graph that AI agents query up to date. Never blocks a commit.',
      '      run: graphify update . > /dev/null 2>&1 || true',
    );
  }
  return `${lines.join('\n')}\n`;
}
